name: Working Example
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.6
        arguments: test testCodeCoverageReport coverallsJacoco
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
